<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/notification/storage/storydata');
phutil_require_module('phabricator', 'applications/notification/storage/subscribed');
phutil_require_module('phabricator', 'storage/queryfx');

phutil_require_module('phutil', 'utils');


phutil_require_source('PhabricatorNotificationQuery.php');
