<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/differential/constants/action');
phutil_require_module('phabricator', 'applications/differential/storage/revision');
phutil_require_module('phabricator', 'applications/notifications/aphlict/base');
phutil_require_module('phabricator', 'applications/notifications/constants/message');
phutil_require_module('phabricator', 'applications/notifications/constants/type');
phutil_require_module('phabricator', 'applications/people/storage/user');

phutil_require_module('phutil', 'utils');


phutil_require_source('DifferentialNotification.php');
