<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/event/storage/base');


phutil_require_source('PhabricatorEventNotification.php');
