<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/maniphest/storage/task');
phutil_require_module('phabricator', 'storage/queryfx');


phutil_require_source('PhabricatorVisualizationTaskCreateQuery.php');
