<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'aphront/writeguard');
phutil_require_module('phabricator', 'applications/notification/storage/base');


phutil_require_source('PhabricatorNotificationSubscribed.php');
