<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/notification/base');
phutil_require_module('phabricator', 'applications/notification/view/story');
phutil_require_module('phabricator', 'applications/project/constants/action');
phutil_require_module('phabricator', 'applications/project/constants/status');


phutil_require_source('PhabricatorNotificationStoryProject.php');
