<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/visualization/controller/base');
phutil_require_module('phabricator', 'applications/visualization/query/taskcreate');


phutil_require_source('PhabricatorVisualizationTestPageController.php');
