<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/notification/constants/base');


phutil_require_source('NotificationMessage.php');
