<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/notifications/aphlict/base');
phutil_require_module('phabricator', 'applications/notifications/constants/message');
phutil_require_module('phabricator', 'applications/notifications/constants/type');


phutil_require_source('ManiphestNotification.php');
