<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/notifications/aphlict/base');
phutil_require_module('phabricator', 'applications/notifications/constants');
phutil_require_module('phabricator', 'applications/people/storage/user');

phutil_require_module('phutil', 'utils');


phutil_require_source('RefreshNotification.php');
